const markerColor = '#007299';
export interface MarkerProps {
  index: number;
  lng: number;
  lat: number;
  height?: number;
  title: string;
  description: string;
  image: string;
  link: string;
  nav?: string;
  color?: string;
}

export const EntertainmentMarkers: MarkerProps[] = [
  {
    index: 0,
    title: 'MCG',
    lng: 144.9837,
    lat: -37.8201,
    height: 100,
    description: 'Sports stadium in Yarra Park, Melbourne',
    image: './images/mcg.jpg',
    link: 'https://www.mcg.org.au/',
    nav: 'https://goo.gl/maps/hk4P6ntHJv2X5gfm9',
    color: markerColor,
  },
  {
    index: 1,
    title: 'Marvel Stadium',
    lng: 144.9465,
    lat: -37.8167,
    description: 'Sports stadium in Docklands, Melbourne',
    image: './images/marvel-stadium.jpg',
    link: 'https://marvelstadium.com.au/',
    nav: 'https://goo.gl/maps/eC8avN6CTKJoPyEPA',
    color: markerColor,
  },
  {
    index: 2,
    title: 'Rod Laver Arena',
    lng: 144.9782,
    lat: -37.8215,
    description: 'Sports arena in Melbourne Park, Melbourne',
    image: './images/rod-laver-arena.jpg',
    link: 'https://rodlaverarena.com.au/',
    nav: 'https://goo.gl/maps/3sE47NdeztTnsRoR8',
    color: markerColor,
  },
  {
    index: 3,
    title: 'AAMI Stadium',
    lng: 144.98380076415168,
    lat: -37.825128281883224,
    description: 'Sports stadium in Melbourne Park, Melbourne',
    image: './images/aami-park.jpg',
    link: 'https://aamipark.com.au/',
    nav: 'https://goo.gl/maps/qeNc95s2oBZYZsNw8',
    color: markerColor,
  },
  {
    index: 4,
    title: "Her Majesty's Theatre",
    lng: 144.9696,
    lat: -37.81,
    description: 'Theatre in the Central Business District, Melbourne',
    image: './images/her-majestys-theatre.jpg',
    link: 'https://hmt.com.au/',
    nav: 'https://goo.gl/maps/hQwz8P5dYV7Fg1vX9',
    color: markerColor,
  },
  {
    index: 5,
    title: 'Princess Theatre',
    lng: 144.9748,
    lat: -37.8119,
    description: 'Theatre in the Central Business District, Melbourne',
    image: './images/princess-theatre.jpg',
    link: 'https://marrinergroup.com.au/venues/princess-theatre',
    nav: 'https://goo.gl/maps/9Rr5z5k5B5Wwz8ZG8',
    color: markerColor,
  },
  {
    index: 6,
    title: 'Athenaeum Theatre',
    lng: 144.9671,
    lat: -37.8151,
    description: 'Theatre in the Central Business District, Melbourne',
    image: './images/athenaeum-theatre.jpg',
    link: 'https://www.athenaeumtheatre.com.au/',
    nav: 'https://goo.gl/maps/TBbBeYc3W8yv9XN26',
    color: markerColor,
  },
  {
    index: 7,
    title: 'State Theatre',
    lng: 144.9683,
    lat: -37.8203,
    description: 'Theatre in the Central Business District, Melbourne',
    image: './images/state-theatre.jpg',
    link: 'https://www.artscentremelbourne.com.au/visit/theatres-and-spaces/state-theatre',
    nav: 'https://goo.gl/maps/itcQ2LJyxb4nMTrC9',
    color: markerColor,
  },
  {
    index: 8,
    title: 'Palais Theatre',
    lng: 144.9760402605205,
    lat: -37.86758277585282,
    description: 'Theatre in St Kilda, Melbourne',
    image: './images/palais-theatre.jpg',
    link: 'https://palaistheatre.com.au/',
    nav: 'https://goo.gl/maps/f8T9AnX9CJ34CCsA7',
    color: markerColor,
  },
  {
    index: 9,
    title: 'Regent Theatre',
    lng: 144.9693,
    lat: -37.8148,
    description: 'Theatre in the Central Business District, Melbourne',
    image: './images/regent-theatre.jpg',
    link: 'https://marrinergroup.com.au/venues/regent-theatre',
    nav: 'https://goo.gl/maps/YhzFYapvPKM1QmuA9',
    color: markerColor,
  },
  {
    index: 10,
    title: 'NGV',
    lng: 144.9674,
    lat: -37.8194,
    description: 'Art museum in the Central Business District, Melbourne',
    image: './images/ngv.jpg',
    link: 'https://www.ngv.vic.gov.au/',
    nav: 'https://goo.gl/maps/iYcrDfzVZdGhsbRx9',
    color: markerColor,
  },
  {
    index: 11,
    title: 'Melbourne Museum',
    lng: 144.9714877817126,
    lat: -37.80475570496132,
    description: 'Museum in Carlton Gardens, Melbourne',
    image: './images/melbourne-museum.jpg',
    link: 'https://museumsvictoria.com.au/melbournemuseum/',
    nav: 'https://goo.gl/maps/48fvRgLK8jyAtsvD6',
    color: markerColor,
  },
  {
    index: 12,
    title: 'Block Arcade',
    lng: 144.9707,
    lat: -37.8158,
    description:
      'Historic shopping arcade in the Central Business District, Melbourne',
    image: './images/block-arcade.jpg',
    link: 'https://theblock.com.au/',
    nav: 'https://goo.gl/maps/2SWCtHmZtKTXBAGT7',
    color: markerColor,
  },
  {
    index: 13,
    title: 'Royal Arcade',
    lng: 144.9614,
    lat: -37.8141,
    description:
      'Historic shopping arcade in the Central Business District, Melbourne',
    image: './images/royal-arcade.jpg',
    link: 'https://royalarcade.com.au/',
    nav: 'https://goo.gl/maps/2SWCtHmZtKTXBAGT7',
    color: markerColor,
  },
  {
    index: 14,
    title: 'QV',
    lng: 144.9636,
    lat: -37.8103,
    description: 'Shopping center in the Central Business District, Melbourne',
    image: './images/qv.jpg',
    link: 'https://www.qv.com.au/',
    nav: 'https://goo.gl/maps/kxKjgoLLz7DRfy2h9',
    color: markerColor,
  },
  {
    index: 15,
    title: 'Melbourne Central',
    lng: 144.9634,
    lat: -37.8107,
    description: 'Shopping center in the Central Business District, Melbourne',
    image: './images/melbourne-central.jpg',
    link: 'https://www.melbournecentral.com.au/home',
    nav: 'https://goo.gl/maps/BXZsBbtcdsivfRFw7',
    color: markerColor,
  },
  {
    index: 16,
    title: 'St Kilda Beach',
    lng: 144.97396556076478,
    lat: -37.86784505673944,
    description: 'Beach in St Kilda, Melbourne',
    image: './images/st-kilda-beach.jpg',
    link: 'https://stkildamelbourne.com.au/things-to-do-see/beach-outdoors/',
    nav: 'https://goo.gl/maps/KNh7VHfjJFakPHth9',
    color: markerColor,
  },
  {
    index: 17,
    title: 'Eureka Tower',
    lng: 144.9639,
    lat: -37.8216,
    description: 'Skyscraper in Southbank, Melbourne',
    image: './images/eureka-tower.jpg',
    link: 'https://www.eurekaskydeck.com.au/',
    nav: 'https://goo.gl/maps/69TxYzKjgKPfBpK17',
    color: markerColor,
  },
  {
    index: 18,
    title: 'Aquarium',
    lng: 151.2007,
    lat: -33.874,
    description: 'Aquarium in Sydney, Australia',
    image: './images/aquarium.jpg',
    link: 'https://www.sydneyaquarium.com.au/',
    nav: 'https://goo.gl/maps/jw7RWYq3zE4jW4Bh6',
    color: markerColor,
  },
  {
    index: 19,
    title: 'IMAX Theatre',
    lng: 144.97044634736366,
    lat: -37.80349189135931,
    description: 'IMAX theatre in Sydney, Australia',
    image: './images/imax-theatre.jpg',
    link: 'https://www.imax.com.au/',
    nav: 'https://goo.gl/maps/2PSxndFCDUkuzsNL6',
    color: markerColor,
  },
  {
    index: 20,
    title: 'Ian Potter Centre',
    lng: 144.9693,
    lat: -37.817,
    description: 'Art museum in Federation Square, Melbourne',
    image: './images/ian-potter-centre.jpg',
    link: 'https://www.ngv.vic.gov.au/ian-potter-centre/',
    nav: 'https://goo.gl/maps/hXieumKjFzv1FXwY6',
    color: markerColor,
  },
  {
    index: 21,
    title: 'ACMI',
    lng: 144.9667,
    lat: -37.8179,
    description:
      'National museum dedicated to the moving image, in Federation Square, Melbourne',
    image: './images/acmi.jpg',
    link: 'https://www.acmi.net.au/',
    nav: 'https://goo.gl/maps/MvU6FhU6bCMCFLNDA',
    color: markerColor,
  },
  {
    index: 22,
    title: 'Royal Botanic Gardens Victoria',
    lng: 144.9792,
    lat: -37.8304,
    description: 'Botanic gardens in Melbourne, Australia',
    image: './images/royal-botanic-gardens.jpg',
    link: 'https://www.rbg.vic.gov.au/',
    nav: 'https://goo.gl/maps/BGwyfj2Qw3pwDXuM9',
    color: markerColor,
  },
  {
    index: 23,
    title: 'Queen Victoria Market',
    lng: 144.9562,
    lat: -37.8075,
    description: 'Market in Melbourne, Australia',
    image: './images/queen-victoria-market.jpg',
    link: 'https://qvm.com.au/',
    nav: 'https://goo.gl/maps/dRZpRJmewKvC8dPz9',
    color: markerColor,
  },
  {
    index: 24,
    title: 'Shrine of Remembrance',
    lng: 144.9739,
    lat: -37.8305,
    description: 'War memorial in Melbourne, Australia',
    image: './images/shrine-of-remembrance.jpg',
    link: 'https://www.shrine.org.au/',
    nav: 'https://goo.gl/maps/4jzD6enB4iq1XU8b7',
    color: markerColor,
  },
];
