import Head from 'next/head';
import Image from 'next/image';
import Map from '../components/Drink';

export default function Home() {
  return (
    <>
      <Head>
        <title>Drink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <div className="h-screen">
      <div className=" w-screen h-[85px] z-10 absolute top-0 left-0 bg-[#bd2238] p-4 text-white flex justify-center items-center">
          <Image src="/images/logo.svg" width={240} height={80} alt={''} />
        </div>
        <Map className="h-full" />
      </div>
    </>
  );
}
