import Head from 'next/head';
import Image from 'next/image';
import Map from '../components/EntertainmentDemo';

export default function Entertainment() {
  return (
    <>
      <Head>
        <title>Entertainment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <div className="z-10 absolute top-0 left-0 w-screen bg-[#b7a896] p-4 text-white flex justify-center items-center">
          <Image src="/images/logo.svg" width={300} height={100} alt={''} />
        </div>
        <Map className="h-full" />
      </div>
    </>
  );
}
