import Head from 'next/head';
import Image from 'next/image';
import Map from '../components/NiramayaWayfinder';

export default function Home() {
  return (
    <>
      <Head>
        <title>Eateries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <Map className="h-full" />
      </div>
    </>
  );
}
